/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as MethodRouteImport } from './routes/method'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SpecimenRouteImport } from './routes/specimen'
import { Route as DDateRouteImport } from './routes/d.$date'
import { Route as PersonIdRouteImport } from './routes/person.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecimenRoute = SpecimenRouteImport.update({
  id: '/specimen',
  path: '/specimen',
  getParentRoute: () => rootRouteImport,
} as any)
const DDateRoute = DDateRouteImport.update({
  id: '/d/$date',
  path: '/d/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/delivery': typeof DeliveryRoute
  '/desk': typeof DeskRoute
  '/method': typeof MethodRoute
  '/ops': typeof OpsRoute
  '/pipeline': typeof PipelineRoute
  '/roster': typeof RosterRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/specimen': typeof SpecimenRoute
  '/d/$date': typeof DDateRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/delivery': typeof DeliveryRoute
  '/desk': typeof DeskRoute
  '/method': typeof MethodRoute
  '/ops': typeof OpsRoute
  '/pipeline': typeof PipelineRoute
  '/roster': typeof RosterRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/specimen': typeof SpecimenRoute
  '/d/$date': typeof DDateRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/delivery': typeof DeliveryRoute
  '/desk': typeof DeskRoute
  '/method': typeof MethodRoute
  '/ops': typeof OpsRoute
  '/pipeline': typeof PipelineRoute
  '/roster': typeof RosterRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/specimen': typeof SpecimenRoute
  '/d/$date': typeof DDateRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/delivery'
    | '/desk'
    | '/method'
    | '/ops'
    | '/pipeline'
    | '/roster'
    | '/search'
    | '/sources'
    | '/specimen'
    | '/d/$date'
    | '/person/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/delivery'
    | '/desk'
    | '/method'
    | '/ops'
    | '/pipeline'
    | '/roster'
    | '/search'
    | '/sources'
    | '/specimen'
    | '/d/$date'
    | '/person/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/delivery'
    | '/desk'
    | '/method'
    | '/ops'
    | '/pipeline'
    | '/roster'
    | '/search'
    | '/sources'
    | '/specimen'
    | '/d/$date'
    | '/person/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  DeliveryRoute: typeof DeliveryRoute
  DeskRoute: typeof DeskRoute
  MethodRoute: typeof MethodRoute
  OpsRoute: typeof OpsRoute
  PipelineRoute: typeof PipelineRoute
  RosterRoute: typeof RosterRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  SpecimenRoute: typeof SpecimenRoute
  DDateRoute: typeof DDateRoute
  PersonIdRoute: typeof PersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specimen': {
      id: '/specimen'
      path: '/specimen'
      fullPath: '/specimen'
      preLoaderRoute: typeof SpecimenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$date': {
      id: '/d/$date'
      path: '/d/$date'
      fullPath: '/d/$date'
      preLoaderRoute: typeof DDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  DeliveryRoute: DeliveryRoute,
  DeskRoute: DeskRoute,
  MethodRoute: MethodRoute,
  OpsRoute: OpsRoute,
  PipelineRoute: PipelineRoute,
  RosterRoute: RosterRoute,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  SpecimenRoute: SpecimenRoute,
  DDateRoute: DDateRoute,
  PersonIdRoute: PersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
